/** A single insight generated by the rule or LLM engine */
export interface Insight {
  id: string;
  type: 'warning' | 'tip' | 'achievement' | 'trend';
  emoji: string;
  title: string;
  description: string;
  priority: number; // 1-10, higher = more important
  category?: string;
}

/** Category spending for a given period */
export interface CategorySpending {
  name: string;
  value: number;
}

/** Aggregated financial data used by both insight engines */
export interface InsightData {
  currentMonth: {
    totalIncome: number;
    totalExpense: number;
    limitExpense: number;
    categories: CategorySpending[];
  };
  lastMonth: {
    totalIncome: number;
    totalExpense: number;
    limitExpense: number;
    categories: CategorySpending[];
  };
  trend6m: { month: string; income: number; expenses: number }[];
  balance: number;
  daysInMonth: number;
  currentDay: number;
  monthlyLimit: number;
  dailyLimit: number;
}
